In [1]:
import pandas as pd
 
# Pollutants data from Environmental Protection Agency
URL = "https://www.epa.gov/sites/default/files/2021-03/state_tier1_caps.xlsx"

In [2]:
# Read the Excel file and print
df = pd.read_excel(URL, sheet_name="State_Trends", header=1)
print("US air pollutant emission data:")
print(df)

US air pollutant emission data:
      State FIPS State  Tier 1 Code      Tier 1 Description Pollutant  \
0              1    AL            1  FUEL COMB. ELEC. UTIL.        CO
1              1    AL            1  FUEL COMB. ELEC. UTIL.       NH3
2              1    AL            1  FUEL COMB. ELEC. UTIL.       NOX
3              1    AL            1  FUEL COMB. ELEC. UTIL.  PM10-PRI
4              1    AL            1  FUEL COMB. ELEC. UTIL.  PM25-PRI
...          ...   ...          ...                     ...       ...
5314          56    WY           16        PRESCRIBED FIRES       NOX
5315          56    WY           16        PRESCRIBED FIRES  PM10-PRI
5316          56    WY           16        PRESCRIBED FIRES  PM25-PRI
5317          56    WY           16        PRESCRIBED FIRES       SO2
5318          56    WY           16        PRESCRIBED FIRES       VOC

      emissions90  emissions96  emissions97  emissions98  emissions99  ...  \
0         6.86859      8.06884      8.04705      8.12158    11.515260  ...
1             NaN      0.01516      0.01605      0.01597     0.016510  ...
2       187.79386    219.00900    209.98918    198.66722   186.387100  ...
3         8.85994      9.28102      8.83472      8.37946    29.217020  ...
4         3.60246      4.36618      4.23529      4.00666    25.092193  ...
...           ...          ...          ...          ...          ...  ...
5314          NaN          NaN          NaN          NaN          NaN  ...
5315          NaN          NaN          NaN          NaN          NaN  ...
5316          NaN          NaN          NaN          NaN          NaN  ...
5317          NaN          NaN          NaN          NaN          NaN  ...
5318          NaN          NaN          NaN          NaN          NaN  ...

      emissions12  emissions13  emissions14  emissions15  emissions16  \
0        9.642311     9.326977     9.011643     9.125182     9.238721
1        0.488463     0.487606     0.486749     0.457457     0.428165
2       57.768312    53.849475    49.930638    40.769235    31.607833
3        6.469981     5.616641     4.763300     3.950869     3.138437
4        4.407621     3.949151     3.490680     2.964636     2.438592
...           ...          ...          ...          ...          ...
5314     2.700751     1.685790     0.670829     0.723065     0.775301
5315    25.776110    16.050751     6.325392     6.152275     5.979158
5316    21.844143    13.602321     5.360500     5.213792     5.067083
5317     1.698021     1.058455     0.418889     0.426659     0.434428
5318    61.320442    38.175952    15.031462    14.476352    13.921243

      emissions17  emissions18  emissions19  emissions20  emissions21
0        9.323161    10.050146     8.243679     8.243679     8.243679
1        0.398873     0.455760     0.417551     0.417551     0.417551
2       22.422130    26.233104    19.592480    13.752790    11.162100
3        2.303326     2.601011     2.868642     2.868642     2.868642
4        1.898368     1.941267     2.659792     2.659792     2.659792
...           ...          ...          ...          ...          ...
5314     0.827537     0.893848     0.374873     0.374873     0.374873
5315     5.806041     7.118097     2.857886     2.857886     2.857886
5316     4.920375     6.032286     2.421937     2.421937     2.421937
5317     0.442197     0.509242     0.208817     0.208817     0.208817
5318    13.366133    16.632343     6.645249     6.645249     6.645249

[5319 rows x 32 columns]

In [3]:
# Show info
print("\nInformation about the DataFrame:")
df.info()

Information about the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5319 entries, 0 to 5318
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State FIPS          5319 non-null   int64
 1   State               5319 non-null   object
 2   Tier 1 Code         5319 non-null   int64
 3   Tier 1 Description  5319 non-null   object
 4   Pollutant           5319 non-null   object
 5   emissions90         3926 non-null   float64
 6   emissions96         4163 non-null   float64
 7   emissions97         4163 non-null   float64
 8   emissions98         4164 non-null   float64
 9   emissions99         4281 non-null   float64
 10  emissions00         4280 non-null   float64
 11  emissions01         4277 non-null   float64
 12  emissions02         4720 non-null   float64
 13  emissions03         4939 non-null   float64
 14  emissions04         4939 non-null   float64
 15  emissions05         4561 non-null   float64
 16  emissions06         4951 non-null   float64
 17  emissions07         4951 non-null   float64
 18  emissions08         4942 non-null   float64
 19  emissions09         5281 non-null   float64
 20  emissions10         5281 non-null   float64
 21  emissions11         5318 non-null   float64
 22  emissions12         5318 non-null   float64
 23  emissions13         5318 non-null   float64
 24  emissions14         5077 non-null   float64
 25  emissions15         5299 non-null   float64
 26  emissions16         5299 non-null   float64
 27  emissions17         5107 non-null   float64
 28  emissions18         5052 non-null   float64
 29  emissions19         5052 non-null   float64
 30  emissions20         5052 non-null   float64
 31  emissions21         5052 non-null   float64
dtypes: float64(27), int64(2), object(3)
memory usage: 1.3+ MB

In [4]:
 
# print dtyes
coltypes = df.dtypes
print("\nColumn data types of the DataFrame:")
print(coltypes)

Column data types of the DataFrame:
State FIPS              int64
State                  object
Tier 1 Code             int64
Tier 1 Description     object
Pollutant              object
emissions90           float64
emissions96           float64
emissions97           float64
emissions98           float64
emissions99           float64
emissions00           float64
emissions01           float64
emissions02           float64
emissions03           float64
emissions04           float64
emissions05           float64
emissions06           float64
emissions07           float64
emissions08           float64
emissions09           float64
emissions10           float64
emissions11           float64
emissions12           float64
emissions13           float64
emissions14           float64
emissions15           float64
emissions16           float64
emissions17           float64
emissions18           float64
emissions19           float64
emissions20           float64
emissions21           float64
dtype: object

In [5]:
# Get last 3 columns
cols = ["State", "Pollutant", "emissions19", "emissions20", "emissions21"]
last3years = df[cols]
print("\nDataFrame of last 3 years data:")
print(last3years)

DataFrame of last 3 years data:
     State Pollutant  emissions19  emissions20  emissions21
0       AL        CO     8.243679     8.243679     8.243679
1       AL       NH3     0.417551     0.417551     0.417551
2       AL       NOX    19.592480    13.752790    11.162100
3       AL  PM10-PRI     2.868642     2.868642     2.868642
4       AL  PM25-PRI     2.659792     2.659792     2.659792
...    ...       ...          ...          ...          ...
5314    WY       NOX     0.374873     0.374873     0.374873
5315    WY  PM10-PRI     2.857886     2.857886     2.857886
5316    WY  PM25-PRI     2.421937     2.421937     2.421937
5317    WY       SO2     0.208817     0.208817     0.208817
5318    WY       VOC     6.645249     6.645249     6.645249

[5319 rows x 5 columns]

In [6]:
# Get a series
data2021 = df["emissions21"]
print("\nSeries of 2021 data:")
print(data2021)

Series of 2021 data:
0        8.243679
1        0.417551
2       11.162100
3        2.868642
4        2.659792
          ...
5314     0.374873
5315     2.857886
5316     2.421937
5317     0.208817
5318     6.645249
Name: emissions21, Length: 5319, dtype: float64

In [7]:
 
# Print unique pollutants
print("\nUnique pollutants:")
print(df["Pollutant"].unique())

Unique pollutants:
['CO' 'NH3' 'NOX' 'PM10-PRI' 'PM25-PRI' 'SO2' 'VOC']

In [8]:
# print mean emission
print("\nMean on the 2021 series:")
print(df["emissions21"].mean())

Mean on the 2021 series:
19.26453203565004

In [9]:
# Describe
print("\nBasic statistics about each column in the DataFrame:")
print(df.describe().T)

Basic statistics about each column in the DataFrame:
              count       mean         std      min        25%        50%  \
State FIPS   5319.0  29.039481   15.667352  1.00000  16.000000  29.000000
Tier 1 Code  5319.0   8.213198    4.610970  1.00000   4.000000   8.000000
emissions90  3926.0  67.885173  373.308888  0.00000   0.474330   4.042665
emissions96  4163.0  54.576353  264.951584  0.00001   0.338420   3.351860
emissions97  4163.0  51.635867  249.057529  0.00001   0.335830   3.339820
emissions98  4164.0  50.801607  240.583301  0.00001   0.344537   3.333940
emissions99  4281.0  48.574331  224.351639  0.00000   0.298280   3.198574
emissions00  4280.0  48.331283  228.045136  0.00000   0.301689   3.191610
emissions01  4277.0  45.379913  208.045773  0.00000   0.306105   3.194570
emissions02  4720.0  40.620586  211.845254  0.00000   0.132365   1.898117
emissions03  4939.0  38.580118  202.907372  0.00000   0.092004   1.646157
emissions04  4939.0  38.266614  199.499755  0.00000   0.092897   1.686734
emissions05  4561.0  37.538785  156.186952  0.00000   0.213054   2.298465
emissions06  4951.0  31.796042  137.208089  0.00000   0.092216   1.557814
emissions07  4951.0  29.166167  127.385372  0.00000   0.084963   1.409892
emissions08  4942.0  31.514819  155.322728  0.00000   0.158240   1.539944
emissions09  5281.0  27.722597  140.524415  0.00000   0.095350   1.339171
emissions10  5281.0  27.461119  140.367131  0.00000   0.094861   1.316531
emissions11  5318.0  26.935748  113.778154  0.00000   0.094116   1.266789
emissions12  5318.0  26.073642  108.279353  0.00000   0.110958   1.347089
emissions13  5318.0  25.211536  103.732749  0.00000   0.111590   1.338692
emissions14  5077.0  24.859033  106.038091  0.00000   0.159116   1.478374
emissions15  5299.0  22.909261  101.590544  0.00000   0.109240   1.223824
emissions16  5299.0  21.357112   96.439660  0.00000   0.102573   1.165098
emissions17  5107.0  24.009949  128.612427  0.00000   0.133070   1.242553
emissions18  5052.0  23.068262  114.948923  0.00000   0.150435   1.373293
emissions19  5052.0  19.846244   98.392126  0.00000   0.125881   1.180123
emissions20  5052.0  19.507828   97.515187  0.00000   0.125066   1.165284
emissions21  5052.0  19.264532   96.702411  0.00000   0.125066   1.151917

                   75%           max
State FIPS   42.000000     56.000000
Tier 1 Code  12.000000     16.000000
emissions90  20.610050  11893.764890
emissions96  16.804540   6890.969060
emissions97  16.679675   6547.791030
emissions98  16.579365   6187.792400
emissions99  16.993275   5701.037970
emissions00  16.240101   5828.319510
emissions01  16.091365   4600.093520
emissions02  12.613465   8402.863427
emissions03  11.613535   8402.863427
emissions04  11.840717   8402.863427
emissions05  13.247740   2903.494222
emissions06  10.265550   2828.242223
emissions07   9.308824   2791.535544
emissions08  10.005629   6461.172958
emissions09   9.098742   6461.172958
emissions10   8.952050   6461.172958
emissions11   9.151551   2333.537512
emissions12   9.311485   2200.097251
emissions13   9.318675   2200.097251
emissions14   9.690808   3239.366102
emissions15   8.506026   3239.366102
emissions16   8.199918   3239.366102
emissions17   8.512386   4514.752701
emissions18   9.013688   4562.151689
emissions19   7.906181   4562.151689
emissions20   7.737705   4562.151689
emissions21   7.754584   4562.151689

In [10]:
# Get CO only
df_CO = df[df["Pollutant"] == "CO"]
print("\nDataFrame of only CO pollutant:")
print(df_CO)

DataFrame of only CO pollutant:
      State FIPS State  Tier 1 Code             Tier 1 Description Pollutant  \
0              1    AL            1         FUEL COMB. ELEC. UTIL.        CO
7              1    AL            2          FUEL COMB. INDUSTRIAL        CO
14             1    AL            3               FUEL COMB. OTHER        CO
21             1    AL            4  CHEMICAL & ALLIED PRODUCT MFG        CO
28             1    AL            5              METALS PROCESSING        CO
...          ...   ...          ...                            ...       ...
5284          56    WY           11               HIGHWAY VEHICLES        CO
5291          56    WY           12                    OFF-HIGHWAY        CO
5298          56    WY           14                  MISCELLANEOUS        CO
5305          56    WY           15                      WILDFIRES        CO
5312          56    WY           16               PRESCRIBED FIRES        CO

      emissions90  emissions96  emissions97  emissions98  emissions99  ...  \
0         6.86859      8.06884      8.04705      8.12158    11.515260  ...
7        25.73799     49.77487     48.15407     48.41578    43.880430  ...
14       89.93378     34.23424     34.29082     34.15163    65.515923  ...
21       54.70092     44.23310     45.59779     46.96713     7.853820  ...
28        6.61641     36.12170     37.64911     36.86870    31.767940  ...
...           ...          ...          ...          ...          ...  ...
5284    356.49009    291.14133    276.70200    262.86346   239.623160  ...
5291     51.96062     56.87244     55.65240     55.65445    56.030470  ...
5298     12.98658   1148.38277    130.10335    109.45384    71.518690  ...
5305          NaN          NaN          NaN          NaN          NaN  ...
5312          NaN          NaN          NaN          NaN          NaN  ...

      emissions12  emissions13  emissions14  emissions15  emissions16  \
0        9.642311     9.326977     9.011643     9.125182     9.238721
7       66.747109    61.629518    56.511926    43.656232    30.800538
14      14.997904    17.892071    20.786239    23.581487    26.376736
21       3.133778     3.144600     3.155423     3.214001     3.272579
28      11.173101    11.354717    11.536333    11.766012    11.995691
...           ...          ...          ...          ...          ...
5284   108.727229   105.535501   102.343774    94.520899    74.799914
5291    42.627693    40.234624    37.841555    35.612352    31.243694
5298     4.619207     2.674452     0.729698     0.703250     0.676802
5305   514.760001   514.760001    17.784989    17.784989    17.784989
5312   260.925351   162.437696    63.950042    61.495748    59.041454

      emissions17  emissions18  emissions19  emissions20  emissions21
0        9.323161    10.050146     8.243679     8.243679     8.243679
7       17.973944    19.148024    17.291741    17.291741    17.291741
14      29.171984    29.207209    29.201838    29.201838    29.201838
21       3.331158     2.774257     2.626484     2.626484     2.626484
28      12.225369    12.534726    12.167189    12.167189    12.167189
...           ...          ...          ...          ...          ...
5284    75.986563    70.776546    69.268149    64.493724    59.719298
5291    30.885597    31.092228    30.594383    30.603392    30.612400
5298     0.650355     3.269705     3.828401     3.828401     3.828401
5305    64.239698   302.235376    89.399972    89.399972    89.399972
5312    56.587161    70.578540    28.177445    28.177445    28.177445

[760 rows x 32 columns]

In [11]:
# Get CO and Highway only
df_CO_HW = df[(df["Pollutant"] == "CO") & (df["Tier 1 Description"] == "HIGHWAY VEHICLES")]
print("\nDataFrame of only CO pollutant from Highway vehicles:")
print(df_CO_HW)

DataFrame of only CO pollutant from Highway vehicles:
      State FIPS State  Tier 1 Code Tier 1 Description Pollutant  emissions90  \
70             1    AL           11   HIGHWAY VEHICLES        CO   2340.75406
171            2    AK           11   HIGHWAY VEHICLES        CO    262.38870
276            4    AZ           11   HIGHWAY VEHICLES        CO   1616.75178
381            5    AR           11   HIGHWAY VEHICLES        CO   1160.47226
486            6    CA           11   HIGHWAY VEHICLES        CO  11893.76489
591            8    CO           11   HIGHWAY VEHICLES        CO   1785.06526
696            9    CT           11   HIGHWAY VEHICLES        CO   1244.74650
800           10    DE           11   HIGHWAY VEHICLES        CO    330.16417
892           11    DC           11   HIGHWAY VEHICLES        CO    141.59974
993           12    FL           11   HIGHWAY VEHICLES        CO   5354.38817
1098          13    GA           11   HIGHWAY VEHICLES        CO   3431.84085
1203          15    HI           11   HIGHWAY VEHICLES        CO    425.80332
1303          16    ID           11   HIGHWAY VEHICLES        CO    569.54601
1408          17    IL           11   HIGHWAY VEHICLES        CO   4363.43728
1513          18    IN           11   HIGHWAY VEHICLES        CO   2635.04348
1618          19    IA           11   HIGHWAY VEHICLES        CO   1367.69745
1723          20    KS           11   HIGHWAY VEHICLES        CO   1288.87435
1828          21    KY           11   HIGHWAY VEHICLES        CO   1759.07154
1933          22    LA           11   HIGHWAY VEHICLES        CO   1483.15211
2037          23    ME           11   HIGHWAY VEHICLES        CO    691.96823
2142          24    MD           11   HIGHWAY VEHICLES        CO   2107.17132
2247          25    MA           11   HIGHWAY VEHICLES        CO   2206.34293
2352          26    MI           11   HIGHWAY VEHICLES        CO   4611.33989
2457          27    MN           11   HIGHWAY VEHICLES        CO   2384.24373
2562          28    MS           11   HIGHWAY VEHICLES        CO   1352.64965
2667          29    MO           11   HIGHWAY VEHICLES        CO   2532.46555
2772          30    MT           11   HIGHWAY VEHICLES        CO    495.69852
2877          31    NE           11   HIGHWAY VEHICLES        CO    814.35388
2982          32    NV           11   HIGHWAY VEHICLES        CO    589.06005
3087          33    NH           11   HIGHWAY VEHICLES        CO    569.19585
3192          34    NJ           11   HIGHWAY VEHICLES        CO   2622.59472
3297          35    NM           11   HIGHWAY VEHICLES        CO   1107.09726
3402          36    NY           11   HIGHWAY VEHICLES        CO   5469.57893
3507          37    NC           11   HIGHWAY VEHICLES        CO   3192.56497
3605          38    ND           11   HIGHWAY VEHICLES        CO    374.54837
3710          39    OH           11   HIGHWAY VEHICLES        CO   4671.94888
3815          40    OK           11   HIGHWAY VEHICLES        CO   1782.07884
3920          41    OR           11   HIGHWAY VEHICLES        CO   1406.34552
4025          42    PA           11   HIGHWAY VEHICLES        CO   4379.79066
4130          44    RI           11   HIGHWAY VEHICLES        CO    353.40443
4235          45    SC           11   HIGHWAY VEHICLES        CO   1910.13433
4340          46    SD           11   HIGHWAY VEHICLES        CO    422.78434
4445          47    TN           11   HIGHWAY VEHICLES        CO   2568.09190
4550          48    TX           11   HIGHWAY VEHICLES        CO   7966.03968
4655          49    UT           11   HIGHWAY VEHICLES        CO   1012.73420
4759          50    VT           11   HIGHWAY VEHICLES        CO    352.11235
4864          51    VA           11   HIGHWAY VEHICLES        CO   3150.89897
4969          53    WA           11   HIGHWAY VEHICLES        CO   2418.35817
5074          54    WV           11   HIGHWAY VEHICLES        CO    833.95126
5179          55    WI           11   HIGHWAY VEHICLES        CO   2094.58886
5284          56    WY           11   HIGHWAY VEHICLES        CO    356.49009

      emissions96  emissions97  emissions98  emissions99  ...  emissions12  \
70     1674.01395   1602.25032   1534.27815   1412.34247  ...   706.703031
171     173.25628    173.86574    175.12039    169.92004  ...    85.189732
276    1084.92615   1065.99933   1049.76456   1017.64515  ...   560.612368
381     913.63369    883.78506    856.08295    798.25244  ...   331.480558
486    6890.96906   6547.79103   6187.79240   5701.03797  ...  1381.401028
591    1356.19722   1311.52565   1269.50309   1186.03591  ...   553.874068
696     809.34899    789.87112    772.66053    727.63672  ...   212.965951
800     215.35512    209.74464    204.66526    192.48549  ...    67.952754
892      93.03482     90.69399     88.57302     83.42699  ...    28.415199
993    3823.98838   3710.72177   3605.81590   3379.56368  ...  1757.496154
1098   2830.11328   2755.46518   2687.67717   2526.59228  ...   993.235375
1203    258.16487    241.24734    224.71093    200.49961  ...   105.529327
1303    446.67839    432.34739    419.08039    391.02866  ...   213.355161
1408   3011.91606   2930.02781   2855.96922   2680.82740  ...   760.796189
1513   2281.76252   2181.49624   2085.98024   1917.22066  ...   788.972683
1618   1037.34539    986.30937    937.33908    855.17077  ...   359.355435
1723    922.86940    880.13182    839.27096    768.86219  ...   353.845851
1828   1362.71065   1329.88058   1300.55259   1225.41437  ...   494.815536
1933   1185.61044   1160.69699   1138.84874   1077.31350  ...   449.281682
2037    454.02670    441.87671    431.64757    404.47975  ...   115.695639
2142   1372.23954   1325.74623   1282.53332   1193.82901  ...   369.358808
2247   1554.62075   1508.18272   1465.72197   1371.52847  ...   322.677819
2352   3379.82364   3233.50539   3094.78772   2845.99797  ...   979.218208
2457   1680.16527   1630.69332   1585.57473   1483.63200  ...   636.954867
2562    972.88991    934.42245    899.64277    830.47743  ...   420.227590
2667   1929.93137   1861.51639   1797.57013   1670.24469  ...   576.913804
2772    373.36808    349.20893    325.64652    290.54790  ...   185.088256
2877    610.64891    586.08546    562.87118    519.74070  ...   242.549309
2982    459.16941    462.05585    465.61464    455.94197  ...   239.449232
3087    389.95802    378.85442    368.80600    345.41332  ...    97.900720
3192   1677.73277   1631.58206   1590.02988   1491.86835  ...   432.628174
3297    781.08565    751.96569    723.53418    673.56442  ...   270.273500
3402   3678.50101   3611.55606   3555.44048   3372.45329  ...   848.892071
3507   2506.55369   2445.57419   2390.87364   2252.67068  ...  1071.909572
3605    288.74356    271.70622    255.18876    229.55456  ...   111.066361
3710   3686.18842   3463.37744   3246.73583   2916.65797  ...  1355.928551
3815   1286.50406   1243.94903   1204.33171   1122.89434  ...   486.982476
3920    963.19124    961.37641    962.69692   1015.65719  ...   414.964951
4025   3232.94007   3103.58264   2981.30780   2754.71896  ...   892.103285
4130    203.98344    204.77044    206.26036    200.44814  ...    63.658872
4235   1311.20373   1289.11442   1270.65159   1207.33670  ...   487.151985
4340    319.88454    297.29578    275.16779    243.27952  ...   126.343183
4445   1908.67469   1856.39575   1809.09063   1697.77831  ...   731.754511
4550   5648.12985   5469.70132   5304.58965   4954.99276  ...  1972.633307
4655    741.32505    709.73590    679.29675    627.18294  ...   270.534808
4759    244.80941    238.11241    232.07494    217.68669  ...    48.405912
4864   2220.05699   2121.15444   2026.82297   1894.83249  ...   612.870036
4969   1575.53651   1523.81512   1475.90993   1375.77946  ...   776.929682
5074    618.75519    598.23481    579.18526    495.40023  ...   181.585946
5179   1872.31714   1783.42817   1698.33757   1553.21286  ...   564.038436
5284    291.14133    276.70200    262.86346    239.62316  ...   108.727229

      emissions13  emissions14  emissions15  emissions16  emissions17  \
70     711.628370   716.553710   682.596952   588.545740   556.784903
171     78.699239    72.208745    70.614685    60.100755    67.426567
276    557.832176   555.051985   549.795535   468.667272   487.903594
381    332.490485   333.500412   322.594562   262.368859   247.804146
486   1176.458345   971.515662   885.596923   793.436556   721.087946
591    525.687743   497.501418   467.711964   376.056262   373.574417
696    209.833435   206.700920   193.667787   157.509839   162.328747
800     71.938429    75.924103    71.298420    65.411964    51.735189
892     31.444741    34.474282    32.768691    24.210790    18.810339
993   1729.595818  1701.695482  1677.027545  1412.279283  1254.926042
1098   966.008247   938.781119   994.707807   818.646413   811.110416
1203   101.630773    97.732218    91.373423    82.599393    78.655834
1303   211.574349   209.793536   197.331418   160.286155   155.822433
1408   840.966562   921.136935   831.139361   724.178863   685.411434
1513   758.077676   727.182669   660.924559   589.246237   562.374211
1618   347.571935   335.788435   323.779397   272.346555   258.822815
1723   345.671628   337.497405   320.392707   262.768809   249.244174
1828   490.650626   486.485716   454.731713   399.169978   378.525577
1933   434.120085   418.958489   392.670113   353.412130   335.524994
2037   113.570079   111.444520   105.338294    85.007458    85.070412
2142   369.648218   369.937628   367.898430   288.389449   282.596907
2247   317.740371   312.802922   299.295746   272.379318   292.921909
2352   910.710123   842.202039   769.753741   697.190584   679.678020
2457   624.883504   612.812142   547.227900   465.402255   469.473166
2562   406.798667   393.369744   373.310301   300.106015   283.869471
2667   626.543452   676.173099   632.996215   551.560145   528.155013
2772   190.051108   195.013959   178.696552   143.928058   142.525830
2877   234.540244   226.531179   214.678776   181.816626   176.603974
2982   220.786267   202.123302   194.198194   177.650835   167.945376
3087    98.163251    98.425782    92.388022    79.400645    78.137684
3192   409.573227   386.518280   368.993308   384.082915   380.322758
3297   249.734797   229.196093   233.137595   199.386778   216.665190
3402   849.872187   850.852302   785.827378   645.088669   548.064572
3507   996.448608   920.987644   882.892193   769.789434   741.407802
3605   110.918368   110.770375    95.943851    74.417982    77.803179
3710  1122.397384   888.866216   822.126834   829.554242   750.402476
3815   457.824118   428.665761   400.765581   390.058156   375.929958
3920   401.952848   388.940744   369.522964   296.375016   301.253382
4025   845.542005   798.980725   740.804896   644.261203   622.784069
4130    62.022886    60.386900    57.091353    45.232114    42.912076
4235   498.034417   508.916850   489.947949   455.156125   450.213884
4340   123.702665   121.062146   112.387868    91.962452    91.465460
4445   723.842657   715.930803   702.269359   584.394817   583.334849
4550  1828.057795  1683.482283  1761.174317  1539.359899  1554.039699
4655   266.621477   262.708146   255.400790   225.231890   205.513270
4759    47.775736    47.145560    44.515796    36.886485    36.762372
4864   658.809925   704.749814   687.014303   578.911416   604.590429
4969   744.614828   712.299974   664.781963   522.044247   537.748345
5074   177.593333   173.600720   165.990382   139.451673   150.103277
5179   550.120339   536.202241   494.694569   391.798117   395.637088
5284   105.535501   102.343774    94.520899    74.799914    75.986563

      emissions18  emissions19  emissions20  emissions21
70     532.140445   518.259811   492.182583   466.105354
171     70.674008    70.674008    63.883471    57.092934
276    433.685363   413.347655   398.958109   384.568563
381    228.213685   227.902883   215.937225   203.971567
486    677.699649   634.022788   590.300174   546.577559
591    324.820353   324.355087   306.685063   289.015039
696    133.374276   129.957343   120.750795   111.544247
800     42.984703    44.868327    42.217957    39.567587
892     20.167554    24.606994    22.510495    20.413995
993   1184.221619  1158.994836  1143.613764  1128.232692
1098   825.697196   731.971771   689.998531   648.025292
1203    74.701252    74.701252    70.638695    66.576138
1303   130.036208   127.182741   119.239140   111.295539
1408   592.438200   565.922158   538.453183   510.984209
1513   516.060233   499.312341   473.758614   448.204886
1618   226.198870   224.873322   211.277527   197.681732
1723   218.856389   213.657319   200.979243   188.301167
1828   337.424734   326.315129   308.202928   290.090728
1933   305.831884   303.878566   288.177230   272.475895
2037    66.912488    64.899072    61.810126    58.721181
2142   243.064385   230.904831   220.212975   209.521118
2247   251.331570   238.063987   219.914128   201.764269
2352   594.864126   564.481547   547.273743   530.065940
2457   385.928400   374.729220   354.684328   334.639436
2562   261.218600   252.552988   239.739443   226.925898
2667   482.066262   491.671372   464.123770   436.576169
2772   119.006568   125.190953   115.368180   105.545406
2877   153.215362   155.068450   145.292512   135.516573
2982   158.180797   151.906366   145.505867   139.105368
3087    66.684191    63.514009    60.777026    58.040044
3192   300.762104   310.910129   285.908341   260.906552
3297   190.034421   189.864264   179.139779   168.415293
3402   438.339505   432.038744   416.290044   400.541345
3507   689.743878   693.025990   643.698262   594.370534
3605    66.358932    65.974017    61.336600    56.699183
3710   626.457462   645.290636   604.091670   562.892705
3815   330.120046   323.950614   304.666351   285.382087
3920   247.152297   226.603952   212.328672   198.053392
4025   516.235799   487.307317   461.928067   436.548818
4130    35.254690    31.515511    30.234478    28.953445
4235   406.590615   404.734420   382.103089   359.471759
4340    76.872934    77.444195    72.340579    67.236964
4445   513.684552   505.845991   480.582476   455.318962
4550  1395.064998  1400.965565  1330.849476  1260.733388
4655   187.777785   181.468363   172.730121   163.991879
4759    26.928297    26.578179    25.418347    24.258516
4864   532.089513   491.868008   469.267757   446.667505
4969   409.654130   395.013372   373.563193   352.113014
5074   133.628312   126.836047   118.621857   110.407667
5179   344.340392   374.804865   342.392977   309.981089
5284    70.776546    69.268149    64.493724    59.719298

[51 rows x 32 columns]

In [12]:
# Get DF of all CO
df_all_co = df[df["Pollutant"]=="CO"][["State", "Tier 1 Description", "emissions21"]]
print("\nDataFrame of only CO pollutant, keep only essential columns:")
print(df_all_co)

DataFrame of only CO pollutant, keep only essential columns:
     State             Tier 1 Description  emissions21
0       AL         FUEL COMB. ELEC. UTIL.     8.243679
7       AL          FUEL COMB. INDUSTRIAL    17.291741
14      AL               FUEL COMB. OTHER    29.201838
21      AL  CHEMICAL & ALLIED PRODUCT MFG     2.626484
28      AL              METALS PROCESSING    12.167189
...    ...                            ...          ...
5284    WY               HIGHWAY VEHICLES    59.719298
5291    WY                    OFF-HIGHWAY    30.612400
5298    WY                  MISCELLANEOUS     3.828401
5305    WY                      WILDFIRES    89.399972
5312    WY               PRESCRIBED FIRES    28.177445

[760 rows x 3 columns]

In [13]:
# Pivot
df_pivot = df_all_co.pivot_table(index="State", columns="Tier 1 Description", values="emissions21")
print("\nPivot table of state vs CO emission source:")
print(df_pivot)

Pivot table of state vs CO emission source:
Tier 1 Description  CHEMICAL & ALLIED PRODUCT MFG  FUEL COMB. ELEC. UTIL.  \
State
AK                                            NaN                4.679098
AL                                       2.626484                8.243679
AR                                       0.307811                5.027354
AZ                                       0.000000                4.483514
CA                                       0.876666                6.819343
CO                                       0.013220                7.410508
CT                                            NaN                0.524795
DC                                            NaN                     NaN
DE                                       0.007891                0.477802
FL                                       0.097017               23.433428
GA                                       0.684786                8.080826
HI                                            NaN                1.480534
IA                                       0.564369               12.197362
ID                                       0.531697                0.240051
IL                                       1.240725               13.672972
IN                                       0.285520               10.263646
KS                                       1.764507               10.661365
KY                                       0.157598               10.088503
LA                                      12.148681               14.124339
MA                                       0.000038                1.126928
MD                                       0.312314                2.119486
ME                                            NaN                2.278409
MI                                       0.169758               13.362612
MN                                       0.106981                6.877005
MO                                       1.531638               15.628293
MS                                       5.683430                9.365678
MT                                       0.239646                2.312470
NC                                       0.587754               12.126342
ND                                       0.034985                5.686924
NE                                       0.085690               12.182681
NH                                            NaN                1.891372
NJ                                       0.080199                2.203424
NM                                            NaN                6.025603
NV                                            NaN                3.312232
NY                                       0.128797                7.255136
OH                                      44.233978                8.349429
OK                                       1.442616               10.631008
OR                                       0.158320                3.709405
PA                                       0.273742               24.852067
RI                                            NaN                0.811315
SC                                       1.218940                7.322689
SD                                            NaN                0.459704
TN                                      14.557758                3.309555
TX                                       7.702839              105.641413
UT                                       0.123703               10.765954
VA                                       0.065439                5.569961
VT                                            NaN                1.343603
WA                                       0.116416                4.831139
WI                                       0.023691                7.422521
WV                                       0.206324                7.836174
WY                                      14.296860               14.617882

Tier 1 Description  FUEL COMB. INDUSTRIAL  FUEL COMB. OTHER  HIGHWAY VEHICLES  \
State
AK                               7.780446        225.802864         57.092934
AL                              17.291741         29.201838        466.105354
AR                              23.058056         46.680001        203.971567
AZ                               1.763194         15.810092        384.568563
CA                              31.690680        149.373372        546.577559
CO                              16.428686         38.713344        289.015039
CT                               2.450608         29.750289        111.544247
DC                               0.012720          0.961035         20.413995
DE                               1.152836          6.360569         39.567587
FL                              23.129794         68.145129       1128.232692
GA                              14.280708         53.868569        648.025292
HI                               0.334582          1.567338         66.576138
IA                              12.285565         29.145228        197.681732
ID                               7.059251         13.012514        111.295539
IL                              30.679828         63.015580        510.984209
IN                              47.888407         59.167689        448.204886
KS                              13.471917         21.164352        188.301167
KY                               9.906762         62.111465        290.090728
LA                              64.427344         11.482425        272.475895
MA                               5.889776         44.074335        201.764269
MD                               3.042098         45.373180        209.521118
ME                              15.231371         57.321036         58.721181
MI                              26.601335         93.024860        530.065940
MN                              16.141919        241.094836        334.639436
MO                               4.572263        113.755732        436.576169
MS                              31.490222         24.616653        226.925898
MT                               6.228669         12.918277        105.545406
NC                              13.016129         72.762770        594.370534
ND                              14.145077          3.987779         56.699183
NE                               7.883224         12.911302        135.516573
NH                               1.472090         33.969574         58.040044
NJ                               1.757294         54.240444        260.906552
NM                              12.925147         27.235088        168.415293
NV                               2.674123         14.647375        139.105368
NY                              12.003073         88.416265        400.541345
OH                              47.924593         96.893341        562.892705
OK                              50.544551         27.794450        285.382087
OR                               9.542326         63.077603        198.053392
PA                              28.708758        112.423239        436.548818
RI                               0.394245          7.298618         28.953445
SC                              24.211264         19.067792        359.471759
SD                               2.808997          7.946983         67.236964
TN                              15.050397         37.196107        455.318962
TX                              81.638084         33.593820       1260.733388
UT                               2.431652          5.988840        163.991879
VA                              17.646621         70.888038        446.667505
VT                               0.451751         38.944224         24.258516
WA                               8.855538         94.161014        352.113014
WI                              22.624203         98.347127        309.981089
WV                               3.424206         76.559679        110.407667
WY                               9.086374          4.758837         59.719298

Tier 1 Description  METALS PROCESSING  MISCELLANEOUS  OFF-HIGHWAY  \
State
AK                           0.050133       1.745362    53.500832
AL                          12.167189      10.657049   191.953551
AR                           6.066433      39.449980   129.115676
AZ                           0.752409       3.229801   207.813693
CA                           0.209140      38.919176   684.594388
CO                           0.786038       4.119938   256.410710
CT                                NaN       0.042294   115.954425
DC                                NaN       0.000294     7.621835
DE                                NaN       1.176028    54.993046
FL                           0.478888     104.483291   984.323902
GA                           0.331833      21.881502   377.970153
HI                                NaN       2.818326    55.297886
IA                           1.924466      21.605200   144.522166
ID                                NaN      26.412383    82.916724
IL                          15.121210      15.788237   462.754659
IN                         177.452115       6.015476   248.134039
KS                           0.450518      50.802767   118.115177
KY                          48.006390       5.642870   134.826763
LA                           0.608223      47.064453   156.081948
MA                           0.000885       0.760621   237.431660
MD                           0.000384       2.679762   222.062553
ME                                NaN       0.032391    90.402100
MI                          21.552851       2.160932   353.941568
MN                           1.337208      18.296012   305.614239
MO                          28.045594      19.839551   242.976324
MS                           2.232720      18.050369    87.402029
MT                           0.000082      16.095612    52.563661
NC                           2.067680      15.978705   381.997845
ND                                NaN      33.498878    74.074781
NE                           0.003541      16.741767    92.984310
NH                                NaN       0.081125    68.430219
NJ                           0.697463       1.501416   308.473166
NM                                NaN       1.076317    66.352453
NV                           0.243328       0.587727   131.935303
NY                          13.112980       0.946060   602.486197
OH                          49.178214       1.664789   415.949121
OK                           1.351137      33.663222   178.482948
OR                           0.836359      17.310480   203.713829
PA                           6.774812       1.328221   420.454755
RI                                NaN       0.007240    29.858772
SC                          32.260816       9.066709   214.348279
SD                           0.014820       3.897571    44.330047
TN                           3.602404       6.361857   231.128570
TX                           9.816256      46.257670   691.656214
UT                           1.218379       1.480525    99.127759
VA                           2.243837       4.256161   314.474413
VT                                NaN       0.033925    33.524583
WA                          30.180620      27.123893   277.544828
WI                           4.687163       3.363907   254.929211
WV                           2.463119       0.109804    55.100967
WY                                NaN       3.828401    30.612400

Tier 1 Description  OTHER INDUSTRIAL PROCESSES  \
State
AK                                    0.492499
AL                                   31.040208
AR                                   11.111067
AZ                                   11.153465
CA                                   26.858656
CO                                    9.976156
CT                                    1.665355
DC                                    0.288114
DE                                    0.420900
FL                                   19.186928
GA                                   20.650256
HI                                    0.561492
IA                                    4.838715
ID                                    7.755837
IL                                    9.887896
IN                                    8.647622
KS                                    4.811562
KY                                    5.354511
LA                                    9.710530
MA                                    3.082738
MD                                    5.422394
ME                                    3.089512
MI                                   10.586854
MN                                    6.085174
MO                                   19.655915
MS                                    5.597183
MT                                    3.321461
NC                                   12.163407
ND                                    4.863326
NE                                    6.545782
NH                                    0.620018
NJ                                    4.440808
NM                                    1.112405
NV                                    2.822302
NY                                    9.738785
OH                                   12.164690
OK                                    4.442472
OR                                    8.156032
PA                                   11.551278
RI                                    0.512679
SC                                   14.293702
SD                                    2.079916
TN                                    8.577556
TX                                   41.678234
UT                                    3.301629
VA                                   13.009885
VT                                    0.305394
WA                                    7.097585
WI                                    7.140186
WV                                    2.294991
WY                                   14.076030

Tier 1 Description  PETROLEUM & RELATED INDUSTRIES  PRESCRIBED FIRES  \
State
AK                                        4.531370        286.474361
AL                                        6.254160        437.438647
AR                                        6.389661        531.262844
AZ                                        0.016421         66.316136
CA                                        2.357080         97.319417
CO                                       38.004429         56.151980
CT                                             NaN          1.124380
DC                                        0.005749               NaN
DE                                        0.919129          4.251235
FL                                        0.942683       1412.506442
GA                                        0.010534        613.763839
HI                                        0.032899          6.622828
IA                                        0.033791         71.375104
ID                                        0.008702        265.092847
IL                                       22.128303        102.010782
IN                                        3.777286         33.819149
KS                                       49.590157        461.799887
KY                                       19.266318         82.949723
LA                                       30.821824        342.674627
MA                                        0.132749          4.005470
MD                                        0.624204         13.819665
ME                                        0.170858          3.938435
MI                                       12.482970         67.182536
MN                                        0.431585        327.868777
MO                                        0.955796        422.089799
MS                                        2.502095        193.449367
MT                                        4.098156        122.193270
NC                                        1.007221        179.255594
ND                                       32.623624         26.194074
NE                                        0.609771         67.550099
NH                                             NaN          0.701549
NJ                                        0.404403         15.392802
NM                                       54.751213         32.632246
NV                                        0.118508          1.704312
NY                                        0.933905          8.313480
OH                                        2.751967         18.884432
OK                                       44.763426        526.350996
OR                                        0.078676        696.720110
PA                                       56.932203         21.803659
RI                                        0.156012          0.093673
SC                                             NaN        283.986487
SD                                        0.185026         35.916759
TN                                        1.633015        126.734040
TX                                      191.356879        790.449347
UT                                       12.332884         57.792369
VA                                        4.970330        110.095027
VT                                             NaN          2.458492
WA                                        0.123340        282.484318
WI                                        0.061928         58.975099
WV                                       30.517494         69.389620
WY                                       26.366124         28.177445

Tier 1 Description  SOLVENT UTILIZATION  STORAGE & TRANSPORT  \
State
AK                                  NaN             0.056500
AL                             0.168992             0.007686
AR                             0.008284             0.004482
AZ                             0.021141             0.011701
CA                             0.432730             0.492900
CO                             0.025924             1.836220
CT                                  NaN                  NaN
DC                                  NaN                  NaN
DE                                  NaN             0.011732
FL                             0.007007             0.103614
GA                             0.023516             0.027574
HI                             0.000541                  NaN
IA                             0.014691             0.052369
ID                                  NaN             0.148006
IL                             0.013515             0.044271
IN                             0.466687             0.021115
KS                             0.009789             0.078006
KY                             0.002794             0.002877
LA                             0.010450             2.483007
MA                             0.026991                  NaN
MD                             0.008429             0.036800
ME                                  NaN             0.001430
MI                                  NaN             0.019716
MN                             0.009444             0.095920
MO                                  NaN             0.058605
MS                             0.047150             0.011560
MT                                  NaN             0.019376
NC                             0.075526             0.086168
ND                                  NaN             0.009500
NE                             0.001510             0.031925
NH                                  NaN                  NaN
NJ                             0.017795             0.025066
NM                             0.000002             0.007120
NV                             0.011099             0.138142
NY                             0.005217             0.007103
OH                             0.083014             0.025362
OK                                  NaN             0.094044
OR                             0.001666             0.007800
PA                             0.044827             0.070707
RI                                  NaN             0.033318

In [14]:
# melt
df_melt = df_pivot.melt(value_name="emissions 2021", var_name="Tier 1 Description", ignore_index=False)
print("\nMelting the pivot table:")
print(df_melt)

Melting the pivot table:
                  Tier 1 Description  emissions 2021
State
AK     CHEMICAL & ALLIED PRODUCT MFG             NaN
AL     CHEMICAL & ALLIED PRODUCT MFG        2.626484
AR     CHEMICAL & ALLIED PRODUCT MFG        0.307811
AZ     CHEMICAL & ALLIED PRODUCT MFG        0.000000
CA     CHEMICAL & ALLIED PRODUCT MFG        0.876666
...                              ...             ...
VT                         WILDFIRES        0.000000
WA                         WILDFIRES      160.284327
WI                         WILDFIRES        0.911783
WV                         WILDFIRES        5.086241
WY                         WILDFIRES       89.399972

[765 rows x 2 columns]

In [15]:
# all three are the same
df_filled = df_pivot.fillna(0)
df_filled = df_pivot.where(df_pivot.notna(), 0)
df_filled = df_pivot.mask(df_pivot.isna(), 0)
print("\nFilled missing value as zero:")
print(df_filled)

Filled missing value as zero:
Tier 1 Description  CHEMICAL & ALLIED PRODUCT MFG  FUEL COMB. ELEC. UTIL.  \
State
AK                                       0.000000                4.679098
AL                                       2.626484                8.243679
AR                                       0.307811                5.027354
AZ                                       0.000000                4.483514
CA                                       0.876666                6.819343
CO                                       0.013220                7.410508
CT                                       0.000000                0.524795
DC                                       0.000000                0.000000
DE                                       0.007891                0.477802
FL                                       0.097017               23.433428
GA                                       0.684786                8.080826
HI                                       0.000000                1.480534
IA                                       0.564369               12.197362
ID                                       0.531697                0.240051
IL                                       1.240725               13.672972
IN                                       0.285520               10.263646
KS                                       1.764507               10.661365
KY                                       0.157598               10.088503
LA                                      12.148681               14.124339
MA                                       0.000038                1.126928
MD                                       0.312314                2.119486
ME                                       0.000000                2.278409
MI                                       0.169758               13.362612
MN                                       0.106981                6.877005
MO                                       1.531638               15.628293
MS                                       5.683430                9.365678
MT                                       0.239646                2.312470
NC                                       0.587754               12.126342
ND                                       0.034985                5.686924
NE                                       0.085690               12.182681
NH                                       0.000000                1.891372
NJ                                       0.080199                2.203424
NM                                       0.000000                6.025603
NV                                       0.000000                3.312232
NY                                       0.128797                7.255136
OH                                      44.233978                8.349429
OK                                       1.442616               10.631008
OR                                       0.158320                3.709405
PA                                       0.273742               24.852067
RI                                       0.000000                0.811315
SC                                       1.218940                7.322689
SD                                       0.000000                0.459704
TN                                      14.557758                3.309555
TX                                       7.702839              105.641413
UT                                       0.123703               10.765954
VA                                       0.065439                5.569961
VT                                       0.000000                1.343603
WA                                       0.116416                4.831139
WI                                       0.023691                7.422521
WV                                       0.206324                7.836174
WY                                      14.296860               14.617882

Tier 1 Description  FUEL COMB. INDUSTRIAL  FUEL COMB. OTHER  HIGHWAY VEHICLES  \
State
AK                               7.780446        225.802864         57.092934
AL                              17.291741         29.201838        466.105354
AR                              23.058056         46.680001        203.971567
AZ                               1.763194         15.810092        384.568563
CA                              31.690680        149.373372        546.577559
CO                              16.428686         38.713344        289.015039
CT                               2.450608         29.750289        111.544247
DC                               0.012720          0.961035         20.413995
DE                               1.152836          6.360569         39.567587
FL                              23.129794         68.145129       1128.232692
GA                              14.280708         53.868569        648.025292
HI                               0.334582          1.567338         66.576138
IA                              12.285565         29.145228        197.681732
ID                               7.059251         13.012514        111.295539
IL                              30.679828         63.015580        510.984209
IN                              47.888407         59.167689        448.204886
KS                              13.471917         21.164352        188.301167
KY                               9.906762         62.111465        290.090728
LA                              64.427344         11.482425        272.475895
MA                               5.889776         44.074335        201.764269
MD                               3.042098         45.373180        209.521118
ME                              15.231371         57.321036         58.721181
MI                              26.601335         93.024860        530.065940
MN                              16.141919        241.094836        334.639436
MO                               4.572263        113.755732        436.576169
MS                              31.490222         24.616653        226.925898
MT                               6.228669         12.918277        105.545406
NC                              13.016129         72.762770        594.370534
ND                              14.145077          3.987779         56.699183
NE                               7.883224         12.911302        135.516573
NH                               1.472090         33.969574         58.040044
NJ                               1.757294         54.240444        260.906552
NM                              12.925147         27.235088        168.415293
NV                               2.674123         14.647375        139.105368
NY                              12.003073         88.416265        400.541345
OH                              47.924593         96.893341        562.892705
OK                              50.544551         27.794450        285.382087
OR                               9.542326         63.077603        198.053392
PA                              28.708758        112.423239        436.548818
RI                               0.394245          7.298618         28.953445
SC                              24.211264         19.067792        359.471759
SD                               2.808997          7.946983         67.236964
TN                              15.050397         37.196107        455.318962
TX                              81.638084         33.593820       1260.733388
UT                               2.431652          5.988840        163.991879
VA                              17.646621         70.888038        446.667505
VT                               0.451751         38.944224         24.258516
WA                               8.855538         94.161014        352.113014
WI                              22.624203         98.347127        309.981089
WV                               3.424206         76.559679        110.407667
WY                               9.086374          4.758837         59.719298

Tier 1 Description  METALS PROCESSING  MISCELLANEOUS  OFF-HIGHWAY  \
State
AK                           0.050133       1.745362    53.500832
AL                          12.167189      10.657049   191.953551
AR                           6.066433      39.449980   129.115676
AZ                           0.752409       3.229801   207.813693
CA                           0.209140      38.919176   684.594388
CO                           0.786038       4.119938   256.410710
CT                           0.000000       0.042294   115.954425
DC                           0.000000       0.000294     7.621835
DE                           0.000000       1.176028    54.993046
FL                           0.478888     104.483291   984.323902
GA                           0.331833      21.881502   377.970153
HI                           0.000000       2.818326    55.297886
IA                           1.924466      21.605200   144.522166
ID                           0.000000      26.412383    82.916724
IL                          15.121210      15.788237   462.754659
IN                         177.452115       6.015476   248.134039
KS                           0.450518      50.802767   118.115177
KY                          48.006390       5.642870   134.826763
LA                           0.608223      47.064453   156.081948
MA                           0.000885       0.760621   237.431660
MD                           0.000384       2.679762   222.062553
ME                           0.000000       0.032391    90.402100
MI                          21.552851       2.160932   353.941568
MN                           1.337208      18.296012   305.614239
MO                          28.045594      19.839551   242.976324
MS                           2.232720      18.050369    87.402029
MT                           0.000082      16.095612    52.563661
NC                           2.067680      15.978705   381.997845
ND                           0.000000      33.498878    74.074781
NE                           0.003541      16.741767    92.984310
NH                           0.000000       0.081125    68.430219
NJ                           0.697463       1.501416   308.473166
NM                           0.000000       1.076317    66.352453
NV                           0.243328       0.587727   131.935303
NY                          13.112980       0.946060   602.486197
OH                          49.178214       1.664789   415.949121
OK                           1.351137      33.663222   178.482948
OR                           0.836359      17.310480   203.713829
PA                           6.774812       1.328221   420.454755
RI                           0.000000       0.007240    29.858772
SC                          32.260816       9.066709   214.348279
SD                           0.014820       3.897571    44.330047
TN                           3.602404       6.361857   231.128570
TX                           9.816256      46.257670   691.656214
UT                           1.218379       1.480525    99.127759
VA                           2.243837       4.256161   314.474413
VT                           0.000000       0.033925    33.524583
WA                          30.180620      27.123893   277.544828
WI                           4.687163       3.363907   254.929211
WV                           2.463119       0.109804    55.100967
WY                           0.000000       3.828401    30.612400

Tier 1 Description  OTHER INDUSTRIAL PROCESSES  \
State
AK                                    0.492499
AL                                   31.040208
AR                                   11.111067
AZ                                   11.153465
CA                                   26.858656
CO                                    9.976156
CT                                    1.665355
DC                                    0.288114
DE                                    0.420900
FL                                   19.186928
GA                                   20.650256
HI                                    0.561492
IA                                    4.838715
ID                                    7.755837
IL                                    9.887896
IN                                    8.647622
KS                                    4.811562
KY                                    5.354511
LA                                    9.710530
MA                                    3.082738
MD                                    5.422394
ME                                    3.089512
MI                                   10.586854
MN                                    6.085174
MO                                   19.655915
MS                                    5.597183
MT                                    3.321461
NC                                   12.163407
ND                                    4.863326
NE                                    6.545782
NH                                    0.620018
NJ                                    4.440808
NM                                    1.112405
NV                                    2.822302
NY                                    9.738785
OH                                   12.164690
OK                                    4.442472
OR                                    8.156032
PA                                   11.551278
RI                                    0.512679
SC                                   14.293702
SD                                    2.079916
TN                                    8.577556
TX                                   41.678234
UT                                    3.301629
VA                                   13.009885
VT                                    0.305394
WA                                    7.097585
WI                                    7.140186
WV                                    2.294991
WY                                   14.076030

Tier 1 Description  PETROLEUM & RELATED INDUSTRIES  PRESCRIBED FIRES  \
State
AK                                        4.531370        286.474361
AL                                        6.254160        437.438647
AR                                        6.389661        531.262844
AZ                                        0.016421         66.316136
CA                                        2.357080         97.319417
CO                                       38.004429         56.151980
CT                                        0.000000          1.124380
DC                                        0.005749          0.000000
DE                                        0.919129          4.251235
FL                                        0.942683       1412.506442
GA                                        0.010534        613.763839
HI                                        0.032899          6.622828
IA                                        0.033791         71.375104
ID                                        0.008702        265.092847
IL                                       22.128303        102.010782
IN                                        3.777286         33.819149
KS                                       49.590157        461.799887
KY                                       19.266318         82.949723
LA                                       30.821824        342.674627
MA                                        0.132749          4.005470
MD                                        0.624204         13.819665
ME                                        0.170858          3.938435
MI                                       12.482970         67.182536
MN                                        0.431585        327.868777
MO                                        0.955796        422.089799
MS                                        2.502095        193.449367
MT                                        4.098156        122.193270
NC                                        1.007221        179.255594
ND                                       32.623624         26.194074
NE                                        0.609771         67.550099
NH                                        0.000000          0.701549
NJ                                        0.404403         15.392802
NM                                       54.751213         32.632246
NV                                        0.118508          1.704312
NY                                        0.933905          8.313480
OH                                        2.751967         18.884432
OK                                       44.763426        526.350996
OR                                        0.078676        696.720110
PA                                       56.932203         21.803659
RI                                        0.156012          0.093673
SC                                        0.000000        283.986487
SD                                        0.185026         35.916759
TN                                        1.633015        126.734040
TX                                      191.356879        790.449347
UT                                       12.332884         57.792369
VA                                        4.970330        110.095027
VT                                        0.000000          2.458492
WA                                        0.123340        282.484318
WI                                        0.061928         58.975099
WV                                       30.517494         69.389620
WY                                       26.366124         28.177445

Tier 1 Description  SOLVENT UTILIZATION  STORAGE & TRANSPORT  \
State
AK                             0.000000             0.056500
AL                             0.168992             0.007686
AR                             0.008284             0.004482
AZ                             0.021141             0.011701
CA                             0.432730             0.492900
CO                             0.025924             1.836220
CT                             0.000000             0.000000
DC                             0.000000             0.000000
DE                             0.000000             0.011732
FL                             0.007007             0.103614
GA                             0.023516             0.027574
HI                             0.000541             0.000000
IA                             0.014691             0.052369
ID                             0.000000             0.148006
IL                             0.013515             0.044271
IN                             0.466687             0.021115
KS                             0.009789             0.078006
KY                             0.002794             0.002877
LA                             0.010450             2.483007
MA                             0.026991             0.000000
MD                             0.008429             0.036800
ME                             0.000000             0.001430
MI                             0.000000             0.019716
MN                             0.009444             0.095920
MO                             0.000000             0.058605
MS                             0.047150             0.011560
MT                             0.000000             0.019376
NC                             0.075526             0.086168
ND                             0.000000             0.009500
NE                             0.001510             0.031925
NH                             0.000000             0.000000
NJ                             0.017795             0.025066
NM                             0.000002             0.007120
NV                             0.011099             0.138142
NY                             0.005217             0.007103
OH                             0.083014             0.025362
OK                             0.000000             0.094044
OR                             0.001666             0.007800
PA                             0.044827             0.070707
RI                             0.000000             0.033318

In [16]:
# aggregation
df_sum = df[df["Pollutant"]=="CO"].groupby("State").sum()
print("\nTotal CO emission by state:")
print(df_sum)

Total CO emission by state:
       State FIPS  Tier 1 Code  emissions90  emissions96  emissions97  \
State
AK             28          115   4502.12238    883.50805   2421.50089
AL             15          123   3404.01163   2440.95216   2369.26803
AR             75          123   1706.69006   1356.08524   1326.53142
AZ             60          123   2563.04249   1876.55422   1752.07274
CA             90          123  15255.07897  11019.29365  10062.82448
CO            120          123   2265.79606   2123.23131   1907.21761
CT            135          123   1544.01353   1173.17385   1147.60725
DC            143          114    156.64046    113.90013    111.42490
DE            150          123    434.93355    330.98650    323.60006
FL            180          123   7479.26112   6048.65349   5949.32661
GA            195          123   5278.20997   4076.22634   3994.38318
HI            225          123    539.19242    369.46352    350.04970
IA            285          123   1739.13729   1426.03757   1368.96482
ID            224          118   1112.07840   3842.91708    929.84520
IL            255          123   5475.55995   4308.18782   4202.00036
IN            270          123   3682.27917   3282.70736   3177.29833
KS            300          123   1942.64784   2290.69382   1488.31949
KY            315          123   2278.98304   1870.74912   1847.59360
LA            330          123   2583.42254   2415.07635   2386.10670
MA            375          123   2746.95118   2238.06597   2175.07598
MD            360          123   2710.56742   2001.72028   1942.72516
ME            345          123   1020.08445    671.80241    660.62084
MI            390          123   5855.31752   4723.68490   4556.46043
MN            405          123   3228.27213   2493.04189   2436.54409
MO            435          123   3316.54710   2767.95511   2609.80599
MS            420          123   2060.14634   1463.58477   1408.65649
MT            450          123    977.26551   1618.92358    767.17205
NC            555          123   4601.38738   4026.55197   3985.27042
ND            532          118    537.20174    541.55217    579.02207
NE            465          123   1128.97431    972.79231    860.42251
NH            495          123    745.40699    574.18989    563.14348
NJ            510          123   3331.24901   2582.09931   2522.96560
NM            525          123   1403.41947   1138.17165   1116.53513
NV            480          123    793.22425   1021.15301    734.45727
NY            540          123   6775.76967   5389.44484   5313.17459
OH            585          123   6460.54644   5627.56944   5419.64892
OK            600          123   2212.31252   2275.15402   1874.68361
OR            615          123   2727.95011   4180.22101   2053.87852
PA            630          123   6454.51859   4766.48539   4654.18895
RI            660          123    429.62814    295.64900    294.39007
SC            675          123   2592.76269   1911.40813   1895.34175
SD            690          123    581.62508    480.61632    437.19239
TN            705          123   3337.29493   2651.08093   2596.66253
TX            720          123  10259.21951   8317.86568   8200.65488
UT            735          123   1315.79283   1350.52217   1042.50231
VA            765          123   3996.42742   3114.60280   3022.13800
VT            750          123    448.30738    339.30571    332.96743
WA            795          123   3604.39515   2852.52146   2662.68284
WI            825          123   2849.49820   2679.75457   2586.76355
WV            810          123   1270.81719    941.39753    921.41038
WY            840          123    467.80484   1598.56712    564.75979

       emissions98  emissions99  emissions00  emissions01  emissions02  ...  \
State                                                                   ...
AK       414.61444  2113.152998   965.370474   318.280263  8689.554049  ...
AL      2361.43903  3011.541333  2265.144310  2151.200553  2139.640782  ...
AR      1345.25313  1293.732544  1253.756263  1232.331321  1182.506250  ...
AZ      1794.73961  2008.201731  1942.665698  1721.562860  2310.468908  ...
CA      9702.05636  8208.233005  9618.345877  7787.477742  5709.540910  ...
CO      1885.17645  1801.101511  2088.859590  1787.469166  2203.830901  ...
CT      1129.55606  1211.390050  1056.026736  1040.091669   929.268392  ...
DC       109.21359   105.198638    90.531250    92.091739    80.682042  ...
DE       319.08832   314.572234   292.168525   296.025553   254.171663  ...
FL      5850.57154  7423.826694  6742.137739  7666.186871  6506.884977  ...
GA      4020.28403  4180.349292  3980.800724  3956.533965  3568.890267  ...
HI       339.71547   354.217189   319.776423   310.105406   265.776330  ...
IA      1318.10395  1257.390179  1253.256175  1228.007040  1115.514167  ...
ID      1227.76612  1382.618079  2841.935135  1190.299926   679.068176  ...
IL      4127.35310  3942.200056  3787.908628  3666.151363  2908.402673  ...
IN      3089.81552  3105.449385  3072.268546  3036.401383  2473.168019  ...
KS      1326.11171  1228.884776  1247.185231  1206.575950  1786.913609  ...
KY      1850.09129  1856.329686  1778.408014  1728.048424  1472.328551  ...
LA      2392.81293  1888.998311  1934.524052  1783.438671  1603.236720  ...
MA      2138.46811  2181.654319  1894.487641  1847.276100  1350.648436  ...
MD      1898.49337  1873.230615  1828.709179  1836.658208  1526.379275  ...
ME       651.48900   593.899443   671.998419   666.388124   565.930511  ...
MI      4428.54156  4079.098537  4122.219512  4000.545833  3624.552898  ...
MN      2434.92790  2495.403846  2498.925920  2342.278709  1713.012948  ...
MO      2536.17393  2520.113498  2487.613208  2352.334216  2235.907125  ...
MS      1416.04024  1373.055687  1485.809204  1386.229183  1069.766284  ...
MT      1106.82999   599.152293  1085.120823   699.537566   563.747786  ...
NC      3976.04553  3839.776425  3777.025178  3783.025129  3093.325841  ...
ND       515.95812   393.562318   375.275447   359.396859   301.993293  ...
NE       798.72661   763.300549   780.866994   706.102861   663.522484  ...
NH       555.19799   552.000541   531.500624   521.688513   430.338678  ...
NJ      2477.24820  2388.482102  2466.005306  2392.789173  1829.382794  ...
NM      1055.37627  1113.708745  2377.885439  1053.734271   752.967187  ...
NV       745.79494  1284.558302   943.678787   880.077765   457.357705  ...
NY      5269.20879  5106.736829  4978.707713  4890.382353  3764.018889  ...
OH      5198.67819  4424.546179  4347.027471  4229.089246  3441.381808  ...
OK      1874.51149  1621.165216  1598.725469  1517.465025  1747.408307  ...
OR      2382.92745  1754.548764  2030.990465  2229.986404  3641.316742  ...
PA      4536.94373  4139.309802  4050.618668  3999.686611  3228.748959  ...
RI       296.48516   287.122275   289.031036   265.760006   174.786610  ...
SC      1900.45156  2107.442698  1821.135081  1826.241676  1679.404043  ...
SD       422.56987   412.970939   690.554386   407.934564   303.892012  ...
TN      2585.12123  2450.793613  2475.410687  2443.962525  2182.665211  ...
TX      8308.87838  7848.551794  7669.459861  7362.184972  6224.173221  ...
UT      1042.11711  1257.046387  1287.414795  1188.920254  1004.818369  ...
VA      2985.18370  2804.349892  2769.161315  2656.487819  2316.838629  ...
VT       328.19500   331.722305   316.911153   388.350253   292.720550  ...
WA      2960.12498  2304.314713  2232.576371  2283.551865  2001.522216  ...
WI      2517.69391  2449.317989  2302.681879  2242.597449  2132.434723  ...
WV       898.70729   841.281326   925.587150   870.513814   702.797149  ...
WY       530.93897   449.954391   819.630096   462.478081   401.647507  ...

       emissions12  emissions13  emissions14  emissions15  emissions16  \
State
AK     2429.632757  2418.607827  2300.045425  2357.437521  2398.158622
AL     1865.985316  1909.107889  1929.506064  1776.102028  1549.953552
AR     1343.550287  1283.565013  1156.753717  1188.363699  1164.566421
AZ     2414.635520  2407.114865  1237.286833  1217.751771  1094.186652
CA     3444.999810  3215.550865  5604.151765  5426.292799  5227.325184
CO     1277.243113  1140.192103   919.899068   892.376857   804.625242
CT      420.925114   410.653308   400.149480   373.715891   315.732768
DC       43.465353    45.381696    47.298038    44.254796    33.298821
DE      127.109054   130.447822   133.389571   131.589801   131.718203
FL     4165.952383  4256.982808  4206.079211  4000.738337  3532.211533
GA     2809.198850  2797.317443  2192.241364  2184.413607  1934.579903
HI      223.690847   254.404623   283.937792   240.986741   196.672864
IA      769.807247   767.609568   772.011519   700.287275   573.909222
ID     1094.727647  1078.814837   987.386057   940.780658   867.839749
IL     1636.595676  1713.307359  1784.680903  1689.120328  1559.188966
IN     1581.729798  1546.458343  1511.074474  1397.795316  1265.579333
KS     1463.636743  1215.591240  1012.643663  1214.808144  1370.953095
KY     1068.773419  1048.487930  1199.042333  1162.014513  1087.751551
LA     2181.620877  2030.509467  1942.231890  1855.307041  1735.828122
MA      709.512010   702.224767   696.377733   661.578110   605.721186
MD      742.978991   733.445929   723.355153   712.124529   611.189793
ME      287.988275   285.953735   284.297556   285.105087   271.790481
MI     1982.956234  1867.938939  1744.856495  1587.068930  1365.093974
MN     2124.698480  2162.257488  1599.119120  1470.709582  1320.695082
MO     1784.524396  1871.898780  1941.764011  1999.981408  2007.992124
MS     1006.881318   963.605845   934.259671   897.055334   790.928012
MT     1315.655501  1310.531345   627.049064   573.614630   500.000598
NC     1816.534255  1740.767530  1636.685322  1579.725836  1432.883935
ND      445.809116   403.106979   357.024043   343.184359   327.280166
NE      501.768549   481.647107   463.576275   460.327160   433.608462
NH      238.645795   232.603474   226.735340   219.518120   203.859319
NJ      911.922592   887.106689   908.050468   865.742970   839.902845
NM     1434.379073  1405.610420   513.487610   514.914857   476.267102
NV      522.893164   497.000357   491.905508   475.889846   452.485780
NY     1910.644231  1895.945884  1884.248029  1737.137880  1465.599728
OH     2406.780850  2136.861740  1882.226418  1740.186445  1631.417533
OK     1781.930918  1618.775362  1311.016985  1345.125189  1396.930560
OR     2069.430406  1854.150128  2291.871520  2217.264798  2089.620283
PA     1836.228457  1767.271694  1714.286475  1611.334678  1443.681846
RI      125.364891   124.689122   124.018908   114.783718    93.892193
SC     1129.520387  1157.962998  1168.364625  1133.531341  1082.313978
SD      660.875695   613.644306   375.728687   332.368607   275.834360
TN     1298.219876  1308.650075  1352.034077  1330.632930  1193.046969
TX     5685.159683  5619.859570  3715.222511  3849.830021  3760.035366
UT      529.313674   512.002752   497.667725   472.069074   418.372217
VA     1323.723083  1378.369798  1408.290506  1376.189888  1249.115979
VT      146.647182   144.965831   143.528824   135.554378   121.753611
WA     1589.880329  1531.784613  2670.332548  2536.212643  2296.065104
WI     1227.017197  1173.315654  1121.268110  1053.614520   898.307407
WV      472.073576   462.042164   502.800156   501.031725   472.318354
WY     1011.528933   900.682591   292.861236   280.296659   253.694516

       emissions17  emissions18  emissions19  emissions20  emissions21
State
AK     4890.110917  5216.369575  5218.919502  5211.711803  5204.504105
AL     1339.803048  1574.068371  1350.711872  1324.945132  1299.178392
AR     1250.079084  1168.110471  1055.635824  1043.724418  1031.813011
AZ     1259.988694  1000.976184   977.916197   964.504353   951.092509
CA     5730.651458  5313.281485  2159.945594  2119.893468  2079.841343
CO      948.933533  1665.751540   856.871643   842.337995   827.804347
CT      315.571878   286.782696   281.918948   272.761686   263.604424
DC       27.621140    29.008520    33.406560    31.356635    29.306709
DE      117.715055   114.158440   114.544620   112.169528   109.794436
FL     3286.488652  3526.297712  3914.458210  3907.647563  3900.836915
GA     1906.631877  2246.711903  2046.709979  2007.374387  1968.038794
HI      154.907538   170.186041   170.557625   166.699103   162.840580
IA      521.311870   625.583293   536.843560   523.073864   509.304168
ID     1988.711592   977.232728   797.517429   789.415208   781.312987
IL     1525.251281  1379.033887  1325.778964  1298.508627  1271.238291
IN     1204.423169  1172.126895  1124.707289  1099.614244  1074.521199
KS     1703.003018   937.987896   970.651528   957.512414   944.373301
KY      901.619977   753.768871   740.388904   722.257403   704.125902
LA     1365.445628  1290.397453  1056.687316  1040.673714  1024.660112
MA      608.098174   568.311467   554.375318   536.451387   518.527457
MD      590.526787   550.948572   544.695840   534.973513   525.251185
ME      282.368636   266.082231   254.291548   250.601302   246.911056
MI     1336.820546  1269.607661  1215.050948  1196.170328  1177.289708
MN     1288.194019  1833.908976  1324.301605  1303.255622  1282.209639
MO     2075.886960  1826.810266  1449.910451  1421.619230  1393.328010
MS      747.559392   810.603315   680.037021   667.001377   653.965734
MT     2646.528561   688.987171   414.807719   404.787215   394.766712
NC     1404.087220  1444.644944  1399.592943  1352.592559  1305.592174
ND      332.829117   289.383696   264.994537   260.149159   255.303780
NE      427.678156   406.797251   379.241403   369.011896   358.782390
NH      202.585240   188.397819   183.866059   181.047766   178.229472
NJ      780.792889   697.014585   717.465880   692.647457   667.829035
NM      624.365899   726.224469   477.241871   466.656630   456.071389
NV      530.133526   781.806322   330.162485   324.451055   318.739626
NY     1323.831319  1223.282936  1212.804877  1201.385815  1189.966753
OH     1503.512562  1382.197906  1390.601093  1349.084559  1307.568024
OK     1724.418451  1748.314382  1257.844329  1239.264117  1220.683904
OR     3445.294339  2698.359940  1412.832746  1400.830723  1388.828700
PA     1386.083820  1289.308327  1251.980140  1226.736593  1201.493046
RI       88.071770    80.920929    75.943590    74.639522    73.335454
SC     1057.987324  1068.302933  1057.916065  1036.249999  1014.583933
SD      414.135345   230.077185   179.506253   174.094708   168.683163
TN     1131.871099  1013.040652  1010.186631   985.585883   960.985134
TX     3782.109066  3638.073727  3551.402720  3482.884404  3414.366089
UT      682.094316   993.597933   469.923025   462.018283   454.113541
VA     1217.830220  1140.440154  1083.923477  1060.934929  1037.946381
VT      116.763166   110.414696   107.613694   106.407657   105.201620
WA     2481.467014  1703.948955  1286.715920  1266.983767  1247.251614
WI      901.126682   922.375165   872.231181   838.232783   804.234385
WV      438.477319   424.120829   395.720171   387.565561   379.410950
WY      298.465277   549.270377   306.461296   301.695879   296.930461

[51 rows x 29 columns]

In [17]:
# group by
df_2021 = ( df.groupby(["State", "Pollutant"])
              .sum()              # get total emissions of each year
              [["emissions21"]]   # select only year 2021
              .reset_index()
              .pivot(index="State", columns="Pollutant", values="emissions21")
              .filter(["CO","SO2"])
          )
print("\nComparing CO and SO2 emission:")
print(df_2021)

Comparing CO and SO2 emission:
Pollutant           CO         SO2
State
AK         5204.504105   32.748621
AL         1299.178392   52.698696
AR         1031.813011   55.288823
AZ          951.092509   15.281760
CA         2079.841343   24.732406
CO          827.804347   13.260101
CT          263.604424    2.425462
DC           29.306709    0.052014
DE          109.794436    1.389199
FL         3900.836915   59.882473
GA         1968.038794   33.024725
HI          162.840580   20.150642
IA          509.304168   65.282897
ID          781.312987    6.585505
IL         1271.238291   79.011126
IN         1074.521199   71.218230
KS          944.373301   16.328289
KY          704.125902   58.015104
LA         1024.660112  110.347085
MA          518.527457    4.766306
MD          525.251185    9.745214
ME          246.911056    4.960069
MI         1177.289708   58.592707
MN         1282.209639   25.418112
MO         1393.328010  120.487980
MS          653.965734   12.034537
MT          394.766712   12.219462
NC         1305.592174   24.877304
ND          255.303780  101.391339
NE          358.782390   44.083668
NH          178.229472    5.635965
NJ          667.829035    2.383347
NM          456.071389   13.751060
NV          318.739626    4.498785
NY         1189.966753   14.576765
OH         1307.568024   91.404494
OK         1220.683904   44.921540
OR         1388.828700    9.833770
PA         1201.493046   74.965259
RI           73.335454    0.861648
SC         1014.583933   22.464962
SD          168.683163    2.969323
TN          960.985134   27.670338
TX         3414.366089  257.526011
UT          454.113541   12.810839
VA         1037.946381   18.252264
VT          105.201620    0.711718
WA         1247.251614   13.178053
WI          804.234385   21.141688
WV          379.410950   49.159621
WY          296.930461   37.056612

In [18]:
# join
df_co = df[df["Pollutant"]=="CO"].groupby("State").sum()[["emissions21"]].rename(columns={"emissions21":"CO"})
df_so2 = df[df["Pollutant"]=="SO2"].groupby("State").sum()[["emissions21"]].rename(columns={"emissions21":"SO2"})
df_joined = df_co.join(df_so2)
print("\nComparing CO and SO2 emission:")
print(df_joined)

Comparing CO and SO2 emission:
                CO         SO2
State
AK     5204.504105   32.748621
AL     1299.178392   52.698696
AR     1031.813011   55.288823
AZ      951.092509   15.281760
CA     2079.841343   24.732406
CO      827.804347   13.260101
CT      263.604424    2.425462
DC       29.306709    0.052014
DE      109.794436    1.389199
FL     3900.836915   59.882473
GA     1968.038794   33.024725
HI      162.840580   20.150642
IA      509.304168   65.282897
ID      781.312987    6.585505
IL     1271.238291   79.011126
IN     1074.521199   71.218230
KS      944.373301   16.328289
KY      704.125902   58.015104
LA     1024.660112  110.347085
MA      518.527457    4.766306
MD      525.251185    9.745214
ME      246.911056    4.960069
MI     1177.289708   58.592707
MN     1282.209639   25.418112
MO     1393.328010  120.487980
MS      653.965734   12.034537
MT      394.766712   12.219462
NC     1305.592174   24.877304
ND      255.303780  101.391339
NE      358.782390   44.083668
NH      178.229472    5.635965
NJ      667.829035    2.383347
NM      456.071389   13.751060
NV      318.739626    4.498785
NY     1189.966753   14.576765
OH     1307.568024   91.404494
OK     1220.683904   44.921540
OR     1388.828700    9.833770
PA     1201.493046   74.965259
RI       73.335454    0.861648
SC     1014.583933   22.464962
SD      168.683163    2.969323
TN      960.985134   27.670338
TX     3414.366089  257.526011
UT      454.113541   12.810839
VA     1037.946381   18.252264
VT      105.201620    0.711718
WA     1247.251614   13.178053
WI      804.234385   21.141688
WV      379.410950   49.159621
WY      296.930461   37.056612

In [19]:
# merge
df_co = df[df["Pollutant"]=="CO"].groupby("State").sum()[["emissions21"]].rename(columns={"emissions21":"CO"}).reset_index()
df_so2 = df[df["Pollutant"]=="SO2"].groupby("State").sum()[["emissions21"]].rename(columns={"emissions21":"SO2"}).reset_index()
df_merged = df_co.merge(df_so2, on="State", how="outer")
print("\nComparing CO and SO2 emission:")
print(df_merged)

Comparing CO and SO2 emission:
   State           CO         SO2
0     AK  5204.504105   32.748621
1     AL  1299.178392   52.698696
2     AR  1031.813011   55.288823
3     AZ   951.092509   15.281760
4     CA  2079.841343   24.732406
5     CO   827.804347   13.260101
6     CT   263.604424    2.425462
7     DC    29.306709    0.052014
8     DE   109.794436    1.389199
9     FL  3900.836915   59.882473
10    GA  1968.038794   33.024725
11    HI   162.840580   20.150642
12    IA   509.304168   65.282897
13    ID   781.312987    6.585505
14    IL  1271.238291   79.011126
15    IN  1074.521199   71.218230
16    KS   944.373301   16.328289
17    KY   704.125902   58.015104
18    LA  1024.660112  110.347085
19    MA   518.527457    4.766306
20    MD   525.251185    9.745214
21    ME   246.911056    4.960069
22    MI  1177.289708   58.592707
23    MN  1282.209639   25.418112
24    MO  1393.328010  120.487980
25    MS   653.965734   12.034537
26    MT   394.766712   12.219462
27    NC  1305.592174   24.877304
28    ND   255.303780  101.391339
29    NE   358.782390   44.083668
30    NH   178.229472    5.635965
31    NJ   667.829035    2.383347
32    NM   456.071389   13.751060
33    NV   318.739626    4.498785
34    NY  1189.966753   14.576765
35    OH  1307.568024   91.404494
36    OK  1220.683904   44.921540
37    OR  1388.828700    9.833770
38    PA  1201.493046   74.965259
39    RI    73.335454    0.861648
40    SC  1014.583933   22.464962
41    SD   168.683163    2.969323
42    TN   960.985134   27.670338
43    TX  3414.366089  257.526011
44    UT   454.113541   12.810839
45    VA  1037.946381   18.252264
46    VT   105.201620    0.711718
47    WA  1247.251614   13.178053
48    WI   804.234385   21.141688
49    WV   379.410950   49.159621
50    WY   296.930461   37.056612

In [20]:
def minmaxyear(subdf):
    sum_series = (subdf.sum()).astype(str)
    year_indices = [x for x in sum_series.index if x.startswith("emissions")]
    minyear = sum_series[year_indices].astype(float).idxmin()
    maxyear = sum_series[year_indices].astype(float).idxmax()
    return pd.Series({"min year": minyear[-2:], "max year": maxyear[-2:]})
 
df_years = df[df["Pollutant"]=="CO"].groupby("State").apply(minmaxyear)
print("\nYears of minimum and maximum emissions:")
print(df_years)

Years of minimum and maximum emissions:
      min year max year
State
AK          07       02
AL          21       90
AR          21       90
AZ          21       90
CA          21       90
CO          16       90
CT          21       90
DC          17       90
DE          21       90
FL          17       01
GA          17       90
HI          17       90
IA          21       90
ID          02       96
IL          21       90
IN          21       90
KS          18       96
KY          21       90
LA          21       05
MA          21       90
MD          21       90
ME          21       90
MI          21       90
MN          21       90
MO          21       90
MS          21       90
MT          21       17
NC          21       90
ND          07       97
NE          21       90
NH          21       90
NJ          21       90
NM          21       00
NV          21       99
NY          21       90
OH          21       90
OK          21       96
OR          21       96
PA          21       90
RI          21       90
SC          21       90
SD          21       11
TN          21       90
TX          21       90
UT          16       96
VA          21       90
VT          21       90
WA          21       90
WI          21       90
WV          21       90
WY          16       96